### ISSUE TITLE
Error when running in python

### ISSUE THREAD

**Issue by andypaul** [serp-ai/ChatGPT-Plugins#1]
I followed the instructions and at the run Setup, I get the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/wm/c0rmwv6x5rn95tg5bh4r71hr0000gn/T/ipykernel_36563/1860396667.py in <module>
      7 from IPython.display import clear_output
      8 
----> 9 from tools import WebSearch, WebBrowser, python_runner
     10 from assistant import OpenAIAssistant

~/Desktop/ChatGPT-Plugins-main/tools.py in <module>
    111 
    112 
--> 113 class WebSearch():
    114     """
    115     Class to handle web search

~/Desktop/ChatGPT-Plugins-main/tools.py in WebSearch()
    122         self.cache = {}
    123 
--> 124     def search(self, keywords: Any, region: str = "us-en", safesearch: str = "Off", time: Any | None = 'y', max_results: Any | None = 20, page: int = 1, output: Any | None = None, download: bool = False, cache: bool = False) -> list:
    125         """
    126         Search

TypeError: unsupported operand type(s) for |: '_SpecialForm' and 'NoneType'

**Comment by francislabountyjr** [comment]
The issue is that the | operand for type hints was not introduced until python 3.10. I changed it to use the `typing` library instead so it should work on older versions of python now. Let me know if it works for you!

**Comment by francislabountyjr** [comment]
Assuming to be fixed, please reopen or create another issue if the issue persists!
