### ISSUE TITLE
move to gpt-3.5?

### ISSUE THREAD

**Issue by KTibow** [serp-ai/ChatGPT-Plugins#2]
was looking to try something like this but i would rather use the chat models since they're better in multiple aspects
however i cant really get them to follow the format, is it possible to get them to work for this?

**Comment by francislabountyjr** [comment]
This was made for the chat models and tested specifically with 3.5-turbo

**Comment by KTibow** [comment]
huh, i couldnt get this to work but it looks like it is using chat completions
